sudo: false
language: node_js
node_js:
    - "12"
    - "node"

cache: npm

env:
    - EXPRESS_VERSION="latest"
    - EXPRESS_VERSION="next"

install:
    - npm install -g codecov
    - npm install -g json
    - json -I -f package.json -e "this.devDependencies.express=\"$EXPRESS_VERSION\""
    - npm install

script:
    - npm test
    - codecov

